PythonProject/PythonProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.views.static import serve #需要导入
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),#这部分很重要
    url(r'^UserInfo/', include('apps.UserInfo.urls', namespace='UserInfo')),  # 用户信息模块
    url(r'^Department/', include('apps.Department.urls', namespace='Department')),  # 科室信息模块
    url(r'^Doctor/', include('apps.Doctor.urls', namespace='Doctor')),  # 医生信息模块
    url(r'^SchoolRecord/', include('apps.SchoolRecord.urls', namespace='SchoolRecord')),  # 学历信息模块
    url(r'^DoctorOrder/', include('apps.DoctorOrder.urls', namespace='DoctorOrder')),  # 医生预约模块
    url(r'^Leaveword/', include('apps.Leaveword.urls', namespace='Leaveword')),  # 留言模块
    url(r'^Notice/', include('apps.Notice.urls', namespace='Notice')),  # 新闻公告模块
    url(r'^Patient/', include('apps.Patient.urls', namespace='Patient')),  # 病人模块

    url(r'^', include("apps.Index.urls", namespace="Index")),  # 首页模块

    url(r'^tinymce/', include('tinymce.urls')),
]

PythonProject/apps/Index/urls.py
from django.conf.urls import url
from apps.Index.views import IndexView,FrontLoginView,FrontLoginOutView,LoginView,LoginOutView,MainView,DoctorMainView,ChangePasswordView

# 正在部署的应用的名称
app_name = 'Index'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),  # 首页
    url(r'^frontLogin$', FrontLoginView.as_view(), name='frontLogin'),  # 前台登录
    url(r'^frontLoginout$', FrontLoginOutView.as_view(), name='frontLoginout'),  # 前台退出
    url(r'^login$', LoginView.as_view(), name="login"),  # 后台登录
    url(r'^loginout$', LoginOutView.as_view(), name="loginout"),  # 后台退出
    url(r'^main$', MainView.as_view(), name='main'),  # 后台主页面
    url(r'^doctorMain$', DoctorMainView.as_view(), name='doctorMain'),  # 后台主页面
    url(r'^changePassword$', ChangePasswordView.as_view(), name='changePassword')  # 管理员修改密码
]

PythonProject/apps/Patient/urls.py
from apps.Patient.views import FrontAddView, FrontListView, UpdateView, DeletesView, FrontShowView, AddView, DoctorAddView, \
    ListView, DoctorListView, OutToExcelView, BackModifyView, FrontModifyView, ListAllView
from django.conf.urls import url

# 正在部署的应用的名称
app_name = 'Patient'

urlpatterns = [
    url(r'^frontAdd$', FrontAddView.as_view(), name='frontAdd'),  # 前台添加
    url(r'^frontModify/(?P<patientId>.+)$', FrontModifyView.as_view(), name='frontModify'),  # 前台更新
    url(r'^frontList$', FrontListView.as_view(), name='frontList'),  # 前台查询列表
    url(r'^frontShow/(?P<patientId>.+)$', FrontShowView.as_view(), name='frontShow'),  # 前台显示详情页
    url(r'^listAll', ListAllView.as_view(), name='listAll'),  # 前台查询所有信息

    url(r'^update/(?P<patientId>.+)$', UpdateView.as_view(), name='update'),  # Ajax方式更新记录

    url(r'^add$', AddView.as_view(), name='add'),  # 后台添加
    url(r'^doctorAdd$', DoctorAddView.as_view(), name='doctorAdd'),  # 后台添加
    url(r'^backModify/(?P<patientId>.+)$', BackModifyView.as_view(), name="backModify"),  # 后台更新
    url(r'^list$', ListView.as_view(), name='list'),  # 后台信息列表
    url(r'^doctorList$', DoctorListView.as_view(), name='doctorList'),  # 后台信息列表
    url(r'^deletes$', DeletesView.as_view(), name="deletes"),  # 删除记录信息
    url(r'^OutToExcel$', OutToExcelView.as_view(), name='OutToExcel')  # 导出信息到excel并下载
]

PythonProject/apps/Patient/models.py
from django.db import models
from apps.Doctor.models import Doctor
from tinymce.models import HTMLField


class Patient(models.Model):
    patientId = models.AutoField(primary_key=True, verbose_name='病人id')
    patientName = models.CharField(max_length=20, default='', verbose_name='病人姓名')
    sex = models.CharField(max_length=4, default='', verbose_name='病人性别')
    cardNumber = models.CharField(max_length=30, default='', verbose_name='身份证号')
    telephone = models.CharField(max_length=20, default='', verbose_name='联系电话')
    illnessCase = HTMLField(max_length=8000, verbose_name='病人病例')
    doctorObj = models.ForeignKey(Doctor,  db_column='doctorObj', on_delete=models.PROTECT, verbose_name='医生')
    addTime = models.CharField(max_length=20, default='', verbose_name='登记时间')

    class Meta:
        db_table = 't_Patient'
        verbose_name = '病人信息'
        verbose_name_plural = verbose_name

    def getJsonObj(self):
        patient = {
            'patientId': self.patientId,
            'patientName': self.patientName,
            'sex': self.sex,
            'cardNumber': self.cardNumber,
            'telephone': self.telephone,
            'illnessCase': self.illnessCase,
            'doctorObj': self.doctorObj.name,
            'doctorObjPri': self.doctorObj.doctorNumber,
            'addTime': self.addTime,
        }
        return patient


PythonProject/apps/Patient/views.py
from django.views.generic import View
from apps.BaseView import BaseView
from django.shortcuts import render
from django.core.paginator import Paginator
from apps.Patient.models import Patient
from apps.Doctor.models import Doctor
from django.http import JsonResponse
from django.http import FileResponse
from apps.BaseView import ImageFormatException
from django.conf import settings
import pandas as pd
import os


class FrontAddView(BaseView):  # 前台病人添加
    def get(self,request):
        doctors = Doctor.objects.all()  # 获取所有医生信息
        context = {
            'doctors': doctors,
        }

        # 使用模板
        return render(request, 'Patient/patient_frontAdd.html', context)

    def post(self, request):
        patient = Patient() # 新建一个病人对象然后获取参数
        patient.patientName = request.POST.get('patient.patientName')
        patient.sex = request.POST.get('patient.sex')
        patient.cardNumber = request.POST.get('patient.cardNumber')
        patient.telephone = request.POST.get('patient.telephone')
        patient.illnessCase = request.POST.get('patient.illnessCase')
        patient.doctorObj = Doctor.objects.get(doctorNumber=request.POST.get('patient.doctorObj.doctorNumber'))
        patient.addTime = request.POST.get('patient.addTime')
        patient.save() # 保存病人信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class FrontModifyView(BaseView):  # 前台修改病人
    def get(self, request, patientId):
        context = {'patientId': patientId}
        return render(request, 'Patient/patient_frontModify.html', context)


class FrontListView(BaseView):  # 前台病人查询列表
    def get(self, request):
        return self.handle(request)

    def post(self, request):
        return self.handle(request)

    def handle(self, request):
        self.getCurrentPage(request)  # 获取当前要显示第几页
        # 下面获取查询参数
        telephone = self.getStrParam(request, 'telephone')
        doctorObj_doctorNumber = self.getStrParam(request, 'doctorObj.doctorNumber')
        addTime = self.getStrParam(request, 'addTime')
        patientName = self.getStrParam(request, 'patientName')
        cardNumber = self.getStrParam(request, 'cardNumber')
        # 然后条件组合查询过滤
        patients = Patient.objects.all()
        if telephone != '':
            patients = patients.filter(telephone__contains=telephone)
        if doctorObj_doctorNumber != '':
            patients = patients.filter(doctorObj=doctorObj_doctorNumber)
        if addTime != '':
            patients = patients.filter(addTime__contains=addTime)
        if patientName != '':
            patients = patients.filter(patientName__contains=patientName)
        if cardNumber != '':
            patients = patients.filter(cardNumber__contains=cardNumber)
        # 对查询结果利用Paginator进行分页
        self.paginator = Paginator(patients, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        patients_page = self.paginator.page(self.currentPage)

        # 获取所有医生信息
        doctors = Doctor.objects.all()
        # 构造模板需要的参数
        context = {
            'doctors': doctors,
            'patients_page': patients_page,
            'telephone': telephone,
            'doctorObj_doctorNumber': doctorObj_doctorNumber,
            'addTime': addTime,
            'patientName': patientName,
            'cardNumber': cardNumber,
            'currentPage': self.currentPage,
            'totalPage': self.totalPage,
            'recordNumber': self.recordNumber,
            'startIndex': self.startIndex,
            'pageList': self.pageList,
        }
        # 渲染模板界面
        return render(request, 'Patient/patient_frontquery_result.html', context)


class FrontShowView(View):  # 前台显示病人详情页
    def get(self, request, patientId):
        # 查询需要显示的病人对象
        patient = Patient.objects.get(patientId=patientId)
        context = {
            'patient': patient
        }
        # 渲染模板显示
        return render(request, 'Patient/patient_frontshow.html', context)


class ListAllView(View): # 前台查询所有病人
    def get(self,request):
        patients = Patient.objects.all()
        patientList = []
        for patient in patients:
            patientObj = {
                'patientId': patient.patientId,
                'patientName': patient.patientName,
            }
            patientList.append(patientObj)
        return JsonResponse(patientList, safe=False)


class UpdateView(BaseView):  # Ajax方式病人更新
    def get(self, request, patientId):
        # GET方式请求查询病人对象并返回病人json格式
        patient = Patient.objects.get(patientId=patientId)
        return JsonResponse(patient.getJsonObj())

    def post(self, request, patientId):
        # POST方式提交病人修改信息更新到数据库
        patient = Patient.objects.get(patientId=patientId)
        patient.patientName = request.POST.get('patient.patientName')
        patient.sex = request.POST.get('patient.sex')
        patient.cardNumber = request.POST.get('patient.cardNumber')
        patient.telephone = request.POST.get('patient.telephone')
        patient.illnessCase = request.POST.get('patient.illnessCase')
        patient.doctorObj = Doctor.objects.get(doctorNumber=request.POST.get('patient.doctorObj.doctorNumber'))
        patient.addTime = request.POST.get('patient.addTime')
        patient.save()
        return JsonResponse({'success': True, 'message': '保存成功'})

class AddView(BaseView):  # 后台病人添加
    def get(self,request):
        doctors = Doctor.objects.all()  # 获取所有医生信息
        context = {
            'doctors': doctors,
        }

        # 渲染显示模板界面
        return render(request, 'Patient/patient_add.html', context)

    def post(self, request):
        # POST方式处理图书添加业务
        patient = Patient() # 新建一个病人对象然后获取参数
        patient.patientName = request.POST.get('patient.patientName')
        patient.sex = request.POST.get('patient.sex')
        patient.cardNumber = request.POST.get('patient.cardNumber')
        patient.telephone = request.POST.get('patient.telephone')
        patient.illnessCase = request.POST.get('patient.illnessCase')
        patient.doctorObj = Doctor.objects.get(doctorNumber=request.POST.get('patient.doctorObj.doctorNumber'))
        patient.addTime = request.POST.get('patient.addTime')
        patient.save() # 保存病人信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class DoctorAddView(BaseView):  # 后台病人添加
    def get(self,request):
        doctors = Doctor.objects.all()  # 获取所有医生信息
        context = {
            'doctors': doctors,
        }

        # 渲染显示模板界面
        return render(request, 'Patient/patient_doctor_add.html', context)

    def post(self, request):
        # POST方式处理图书添加业务
        patient = Patient() # 新建一个病人对象然后获取参数
        patient.patientName = request.POST.get('patient.patientName')
        patient.sex = request.POST.get('patient.sex')
        patient.cardNumber = request.POST.get('patient.cardNumber')
        patient.telephone = request.POST.get('patient.telephone')
        patient.illnessCase = request.POST.get('patient.illnessCase')
        patient.doctorObj = Doctor.objects.get(doctorNumber=request.session.get('doctorNumber'))
        patient.addTime = request.POST.get('patient.addTime')
        patient.save() # 保存病人信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class BackModifyView(BaseView):  # 后台更新病人
    def get(self, request, patientId):
        context = {'patientId': patientId}
        return render(request, 'Patient/patient_modify.html', context)



class ListView(BaseView):  # 后台病人列表
    def get(self, request):
        # 使用模板
        return render(request, 'Patient/patient_query_result.html')

    def post(self, request):
        # 获取当前要显示第几页和每页几条数据
        self.getPageAndSize(request)
        # 收集查询参数
        telephone = self.getStrParam(request, 'telephone')
        doctorObj_doctorNumber = self.getStrParam(request, 'doctorObj.doctorNumber')
        addTime = self.getStrParam(request, 'addTime')
        patientName = self.getStrParam(request, 'patientName')
        cardNumber = self.getStrParam(request, 'cardNumber')
        # 然后条件组合查询过滤
        patients = Patient.objects.all()
        if telephone != '':
            patients = patients.filter(telephone__contains=telephone)
        if doctorObj_doctorNumber != '':
            patients = patients.filter(doctorObj=doctorObj_doctorNumber)
        if addTime != '':
            patients = patients.filter(addTime__contains=addTime)
        if patientName != '':
            patients = patients.filter(patientName__contains=patientName)
        if cardNumber != '':
            patients = patients.filter(cardNumber__contains=cardNumber)
        # 利用Paginator对查询结果集分页
        self.paginator = Paginator(patients, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        patients_page = self.paginator.page(self.currentPage)
        # 查询的结果集转换为列表
        patientList = []
        for patient in patients_page:
            patient = patient.getJsonObj()
            patientList.append(patient)
        # 构造模板页面需要的参数
        patient_res = {
            'rows': patientList,
            'total': self.recordNumber,
        }
        # 渲染模板页面显示
        return JsonResponse(patient_res, json_dumps_params={'ensure_ascii':False})


class DoctorListView(BaseView):  # 后台病人列表
    def get(self, request):
        # 使用模板
        return render(request, 'Patient/patient_doctorQuery_result.html')

    def post(self, request):
        # 获取当前要显示第几页和每页几条数据
        self.getPageAndSize(request)
        # 收集查询参数
        telephone = self.getStrParam(request, 'telephone')
        doctorObj_doctorNumber = request.session.get('doctorNumber')
        addTime = self.getStrParam(request, 'addTime')

PythonProject/templates/Patient/patient_frontAdd.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
<title>病人添加</title>
<link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
<link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
<link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" media="screen">
</head>
<body style="margin-top:70px;">
{% include 'header.html' %}
<div class="container">
	<div class="row">
		<div class="col-md-12 wow fadeInUp" data-wow-duration="0.5s">
			<div>
				<!-- Nav tabs -->
				<ul class="nav nav-tabs" role="tablist">
			    	<li role="presentation" ><a href="{% url 'Patient:frontList' %}">病人列表</a></li>
			    	<li role="presentation" class="active"><a href="#patientAdd" aria-controls="patientAdd" role="tab" data-toggle="tab">添加病人</a></li>
				</ul>
				<!-- Tab panes -->
				<div class="tab-content">
				    <div role="tabpanel" class="tab-pane" id="patientList">
				    </div>
				    <div role="tabpanel" class="tab-pane active" id="patientAdd"> 
				      	<form class="form-horizontal" name="patientAddForm" id="patientAddForm" enctype="multipart/form-data" method="post"  class="mar_t15">
				    {% csrf_token %}
						  <div class="form-group">
						  	 <label for="patient_patientName" class="col-md-2 text-right">病人姓名:</label>
						  	 <div class="col-md-8">
							    <input type="text" id="patient_patientName" name="patient.patientName" class="form-control" placeholder="请输入病人姓名">
							 </div>
						  </div>
						  <div class="form-group">
						  	 <label for="patient_sex" class="col-md-2 text-right">病人性别:</label>
						  	 <div class="col-md-8">
							    <input type="text" id="patient_sex" name="patient.sex" class="form-control" placeholder="请输入病人性别">
							 </div>
						  </div>
						  <div class="form-group">
						  	 <label for="patient_cardNumber" class="col-md-2 text-right">身份证号:</label>
						  	 <div class="col-md-8">
							    <input type="text" id="patient_cardNumber" name="patient.cardNumber" class="form-control" placeholder="请输入身份证号">
							 </div>
						  </div>
						  <div class="form-group">
						  	 <label for="patient_telephone" class="col-md-2 text-right">联系电话:</label>
						  	 <div class="col-md-8">
							    <input type="text" id="patient_telephone" name="patient.telephone" class="form-control" placeholder="请输入联系电话">
							 </div>
						  </div>
						  <div class="form-group">
						  	 <label for="patient_illnessCase" class="col-md-2 text-right">病人病例:</label>
						  	 <div class="col-md-8">
							    <textarea name="patient.illnessCase" id="patient_illnessCase" style="width:100%;height:350px;"></textarea>
							 </div>
						  </div>
						  <div class="form-group">
						  	 <label for="patient_doctorObj_doctorNumber" class="col-md-2 text-right">医生:</label>
						  	 <div class="col-md-8">
							    <select id="patient_doctorObj_doctorNumber" name="patient.doctorObj.doctorNumber" class="form-control">
                            {% for doctor in doctors %}
                            <option value="{{ doctor.doctorNumber }}">{{ doctor.name }}</option>
                            {% endfor %}
							    </select>
						  	 </div>
						  </div>
						  <div class="form-group">
						  	 <label for="patient_addTimeDiv" class="col-md-2 text-right">登记时间:</label>
						  	 <div class="col-md-8">
				                <div id="patient_addTimeDiv" class="input-group date patient_addTime col-md-12" data-link-field="patient_addTime">
				                    <input class="form-control" id="patient_addTime" name="patient.addTime" size="16" type="text" value="" placeholder="请选择登记时间" readonly>
				                    <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
				                    <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
				                </div>
						  	 </div>
						  </div>
				          <div class="form-group">
				             <span class="col-md-2"></span>
				             <span onclick="ajaxPatientAdd();" class="btn btn-primary bottom5 top5">添加</span>
				          </div>
						</form> 
				        <style>#patientAddForm .form-group {margin:10px;}  </style>
					</div>
				</div>
			</div>
		</div>
	</div> 
</div>

{% include 'footer.html' %}
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'plugins/wow.min.js' %}"></script>
<script src="{% static 'plugins/bootstrapvalidator/js/bootstrapValidator.min.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/bootstrap-datetimepicker.min.js' %}" charset="UTF-8"></script>
<script type="text/javascript" src="{% static 'plugins/locales/bootstrap-datetimepicker.zh-CN.js' %}" charset="UTF-8"></script>
<script src="{% static 'tiny_mce/tiny_mce.js' %}"></script>
<script>
    //实例化病人病例编辑器
    tinyMCE.init({
        selector: "#patient_illnessCase",
        theme: 'advanced',
        language: "zh",
        strict_loading_mode: 1,
    });
	//提交添加病人信息
	function ajaxPatientAdd() { 
		//提交之前先验证表单
		$("#patientAddForm").data('bootstrapValidator').validate();
		if(!$("#patientAddForm").data('bootstrapValidator').isValid()){
			return;
		}
		jQuery.ajax({
			type : "post",
			url : "{% url 'Patient:frontAdd' %}",
			dataType : "json" , 
			data: new FormData($("#patientAddForm")[0]),
			success : function(obj) {
				if(obj.success){ 
					alert("保存成功！");
					location.reload();
				} else {
					alert(obj.message);
				}
			},
			processData: false, 
			contentType: false, 
		});
	} 
$(function(){
	/*小屏幕导航点击关闭菜单*/
    $('.navbar-collapse a').click(function(){
        $('.navbar-collapse').collapse('hide');
    });
    new WOW().init();
	//验证病人添加表单字段
	$('#patientAddForm').bootstrapValidator({
		feedbackIcons: {
			valid: 'glyphicon glyphicon-ok',
			invalid: 'glyphicon glyphicon-remove',
			validating: 'glyphicon glyphicon-refresh'
		},
		fields: {
			"patient.patientName": {
				validators: {
					notEmpty: {
						message: "病人姓名不能为空",
					}
				}
			},
			"patient.sex": {
				validators: {
					notEmpty: {
						message: "病人性别不能为空",
					}
				}
			},
			"patient.cardNumber": {
				validators: {
					notEmpty: {
						message: "身份证号不能为空",
					}
				}
			},
			"patient.telephone": {
				validators: {
					notEmpty: {
						message: "联系电话不能为空",
					}
				}
			},
			"patient.addTime": {
				validators: {
					notEmpty: {
						message: "登记时间不能为空",
					}
				}
			},
		}
	}); 
	//登记时间组件
	$('#patient_addTimeDiv').datetimepicker({
		language:  'zh-CN',  //显示语言
		format: 'yyyy-mm-dd hh:ii:ss',
		weekStart: 1,
		todayBtn:  1,
		autoclose: 1,
		minuteStep: 1,
		todayHighlight: 1,
		startView: 2,
		forceParse: 0
	}).on('hide',function(e) {
		//下面这行代码解决日期组件改变日期后不验证的问题
		$('#patientAddForm').data('bootstrapValidator').updateStatus('patient.addTime', 'NOT_VALIDATED',null).validateField('patient.addTime');
	});
})
</script>
</body>
</html>

PythonProject/templates/Patient/patient_frontshow.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
  <TITLE>查看病人详情</TITLE>
  <link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
  <link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
  <link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
  <link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
</head>
<body style="margin-top:70px;"> 
{% include 'header.html' %}
<div class="container">
	<ul class="breadcrumb">
  		<li><a href={% url 'Index:index' %}">首页</a></li>
  		<li><a href="{% url 'Patient:frontList' %}">病人信息</a></li>
  		<li class="active">详情查看</li>
	</ul>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">病人id:</div>
		<div class="col-md-10 col-xs-6">{{ patient.patientId }}</div>
	</div>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">病人姓名:</div>
		<div class="col-md-10 col-xs-6">{{ patient.patientName }}</div>
	</div>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">病人性别:</div>
		<div class="col-md-10 col-xs-6">{{ patient.sex }}</div>
	</div>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">身份证号:</div>
		<div class="col-md-10 col-xs-6">{{ patient.cardNumber }}</div>
	</div>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">联系电话:</div>
		<div class="col-md-10 col-xs-6">{{ patient.telephone }}</div>
	</div>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">病人病例:</div>
		<div class="col-md-10 col-xs-6">{{ patient.illnessCase | safe  }}</div>
	</div>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">医生:</div>
		<div class="col-md-10 col-xs-6">{{ patient.doctorObj.name }}</div>
	</div>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">登记时间:</div>
		<div class="col-md-10 col-xs-6">{{ patient.addTime }}</div>
	</div>
	<div class="row bottom15">
		<div class="col-md-2 col-xs-4"></div>
		<div class="col-md-6 col-xs-6">
			<button onclick="history.back();" class="btn btn-primary">返回</button>
		</div>
	</div>
</div> 
{% include 'footer.html' %}
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'plugins/wow.min.js' %}"></script>
<script>
$(function(){
        /*小屏幕导航点击关闭菜单*/
        $('.navbar-collapse a').click(function(){
            $('.navbar-collapse').collapse('hide');
        });
        new WOW().init();
 })
 </script> 
</body>
</html>
