PythonProject/PythonProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.views.static import serve #需要导入
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),#这部分很重要
    url(r'^UserInfo/', include('apps.UserInfo.urls', namespace='UserInfo')),  # 用户信息模块
    url(r'^Department/', include('apps.Department.urls', namespace='Department')),  # 科室信息模块
    url(r'^Doctor/', include('apps.Doctor.urls', namespace='Doctor')),  # 医生信息模块
    url(r'^SchoolRecord/', include('apps.SchoolRecord.urls', namespace='SchoolRecord')),  # 学历信息模块
    url(r'^DoctorOrder/', include('apps.DoctorOrder.urls', namespace='DoctorOrder')),  # 医生预约模块
    url(r'^Leaveword/', include('apps.Leaveword.urls', namespace='Leaveword')),  # 留言模块
    url(r'^Notice/', include('apps.Notice.urls', namespace='Notice')),  # 新闻公告模块
    url(r'^Patient/', include('apps.Patient.urls', namespace='Patient')),  # 病人模块

    url(r'^', include("apps.Index.urls", namespace="Index")),  # 首页模块

    url(r'^tinymce/', include('tinymce.urls')),
]

PythonProject/apps/Department/urls.py
from apps.Department.views import FrontAddView, FrontListView, UpdateView, DeletesView, FrontShowView, AddView, \
    ListView, OutToExcelView, BackModifyView, FrontModifyView, ListAllView
from django.conf.urls import url

# 正在部署的应用的名称
app_name = 'Department'

urlpatterns = [
    url(r'^frontAdd$', FrontAddView.as_view(), name='frontAdd'),  # 前台添加
    url(r'^frontModify/(?P<departmentNo>.+)$', FrontModifyView.as_view(), name='frontModify'),  # 前台更新
    url(r'^frontList$', FrontListView.as_view(), name='frontList'),  # 前台查询列表
    url(r'^frontShow/(?P<departmentNo>.+)$', FrontShowView.as_view(), name='frontShow'),  # 前台显示详情页
    url(r'^listAll', ListAllView.as_view(), name='listAll'),  # 前台查询所有信息

    url(r'^update/(?P<departmentNo>.+)$', UpdateView.as_view(), name='update'),  # Ajax方式更新记录

    url(r'^add$', AddView.as_view(), name='add'),  # 后台添加
    url(r'^backModify/(?P<departmentNo>.+)$', BackModifyView.as_view(), name="backModify"),  # 后台更新
    url(r'^list$', ListView.as_view(), name='list'),  # 后台信息列表
    url(r'^deletes$', DeletesView.as_view(), name="deletes"),  # 删除记录信息
    url(r'^OutToExcel$', OutToExcelView.as_view(), name='OutToExcel')  # 导出信息到excel并下载
]

PythonProject/apps/Index/urls.py
from django.conf.urls import url
from apps.Index.views import IndexView,FrontLoginView,FrontLoginOutView,LoginView,LoginOutView,MainView,DoctorMainView,ChangePasswordView

# 正在部署的应用的名称
app_name = 'Index'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),  # 首页
    url(r'^frontLogin$', FrontLoginView.as_view(), name='frontLogin'),  # 前台登录
    url(r'^frontLoginout$', FrontLoginOutView.as_view(), name='frontLoginout'),  # 前台退出
    url(r'^login$', LoginView.as_view(), name="login"),  # 后台登录
    url(r'^loginout$', LoginOutView.as_view(), name="loginout"),  # 后台退出
    url(r'^main$', MainView.as_view(), name='main'),  # 后台主页面
    url(r'^doctorMain$', DoctorMainView.as_view(), name='doctorMain'),  # 后台主页面
    url(r'^changePassword$', ChangePasswordView.as_view(), name='changePassword')  # 管理员修改密码
]

PythonProject/apps/Department/models.py
from django.db import models
from tinymce.models import HTMLField


class Department(models.Model):
    departmentNo = models.CharField(max_length=20, default='', primary_key=True, verbose_name='科室编号')
    departmentName = models.CharField(max_length=20, default='', verbose_name='科室名称')
    madeDate = models.CharField(max_length=20, default='', verbose_name='成立日期')
    telephone = models.CharField(max_length=20, default='', verbose_name='联系电话')
    chargeMan = models.CharField(max_length=20, default='', verbose_name='负责人')
    departmentDesc = HTMLField(max_length=8000, verbose_name='科室介绍')

    class Meta:
        db_table = 't_Department'
        verbose_name = '科室信息信息'
        verbose_name_plural = verbose_name

    def getJsonObj(self):
        department = {
            'departmentNo': self.departmentNo,
            'departmentName': self.departmentName,
            'madeDate': self.madeDate,
            'telephone': self.telephone,
            'chargeMan': self.chargeMan,
            'departmentDesc': self.departmentDesc,
        }
        return department


PythonProject/apps/Department/views.py
from django.views.generic import View
from apps.BaseView import BaseView
from django.shortcuts import render
from django.core.paginator import Paginator
from apps.Department.models import Department
from django.http import JsonResponse
from django.http import FileResponse
from apps.BaseView import ImageFormatException
from django.conf import settings
import pandas as pd
import os


class FrontAddView(BaseView):  # 前台科室信息添加
    def primaryKeyExist(self, departmentNo):  # 判断主键是否存在
        try:
            Department.objects.get(departmentNo=departmentNo)
            return True
        except Department.DoesNotExist:
            return False

    def get(self,request):

        # 使用模板
        return render(request, 'Department/department_frontAdd.html')

    def post(self, request):
        departmentNo = request.POST.get('department.departmentNo') # 判断科室编号是否存在
        if self.primaryKeyExist(departmentNo):
            return JsonResponse({'success': False, 'message': '科室编号已经存在'})

        department = Department() # 新建一个科室信息对象然后获取参数
        department.departmentNo = departmentNo
        department.departmentName = request.POST.get('department.departmentName')
        department.madeDate = request.POST.get('department.madeDate')
        department.telephone = request.POST.get('department.telephone')
        department.chargeMan = request.POST.get('department.chargeMan')
        department.departmentDesc = request.POST.get('department.departmentDesc')
        department.save() # 保存科室信息信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class FrontModifyView(BaseView):  # 前台修改科室信息
    def get(self, request, departmentNo):
        context = {'departmentNo': departmentNo}
        return render(request, 'Department/department_frontModify.html', context)


class FrontListView(BaseView):  # 前台科室信息查询列表
    def get(self, request):
        return self.handle(request)

    def post(self, request):
        return self.handle(request)

    def handle(self, request):
        self.getCurrentPage(request)  # 获取当前要显示第几页
        # 下面获取查询参数
        departmentNo = self.getStrParam(request, 'departmentNo')
        departmentName = self.getStrParam(request, 'departmentName')
        madeDate = self.getStrParam(request, 'madeDate')
        chargeMan = self.getStrParam(request, 'chargeMan')
        # 然后条件组合查询过滤
        departments = Department.objects.all()
        if departmentNo != '':
            departments = departments.filter(departmentNo__contains=departmentNo)
        if departmentName != '':
            departments = departments.filter(departmentName__contains=departmentName)
        if madeDate != '':
            departments = departments.filter(madeDate__contains=madeDate)
        if chargeMan != '':
            departments = departments.filter(chargeMan__contains=chargeMan)
        # 对查询结果利用Paginator进行分页
        self.paginator = Paginator(departments, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        departments_page = self.paginator.page(self.currentPage)

        # 构造模板需要的参数
        context = {
            'departments_page': departments_page,
            'departmentNo': departmentNo,
            'departmentName': departmentName,
            'madeDate': madeDate,
            'chargeMan': chargeMan,
            'currentPage': self.currentPage,
            'totalPage': self.totalPage,
            'recordNumber': self.recordNumber,
            'startIndex': self.startIndex,
            'pageList': self.pageList,
        }
        # 渲染模板界面
        return render(request, 'Department/department_frontquery_result.html', context)


class FrontShowView(View):  # 前台显示科室信息详情页
    def get(self, request, departmentNo):
        # 查询需要显示的科室信息对象
        department = Department.objects.get(departmentNo=departmentNo)
        context = {
            'department': department
        }
        # 渲染模板显示
        return render(request, 'Department/department_frontshow.html', context)


class ListAllView(View): # 前台查询所有科室信息
    def get(self,request):
        departments = Department.objects.all()
        departmentList = []
        for department in departments:
            departmentObj = {
                'departmentNo': department.departmentNo,
                'departmentName': department.departmentName,
            }
            departmentList.append(departmentObj)
        return JsonResponse(departmentList, safe=False)


class UpdateView(BaseView):  # Ajax方式科室信息更新
    def get(self, request, departmentNo):
        # GET方式请求查询科室信息对象并返回科室信息json格式
        department = Department.objects.get(departmentNo=departmentNo)
        return JsonResponse(department.getJsonObj())

    def post(self, request, departmentNo):
        # POST方式提交科室信息修改信息更新到数据库
        department = Department.objects.get(departmentNo=departmentNo)
        department.departmentName = request.POST.get('department.departmentName')
        department.madeDate = request.POST.get('department.madeDate')
        department.telephone = request.POST.get('department.telephone')
        department.chargeMan = request.POST.get('department.chargeMan')
        department.departmentDesc = request.POST.get('department.departmentDesc')
        department.save()
        return JsonResponse({'success': True, 'message': '保存成功'})

class AddView(BaseView):  # 后台科室信息添加
    def primaryKeyExist(self, departmentNo):  # 判断主键是否存在
        try:
            Department.objects.get(departmentNo=departmentNo)
            return True
        except Department.DoesNotExist:
            return False

    def get(self,request):

        # 渲染显示模板界面
        return render(request, 'Department/department_add.html')

    def post(self, request):
        # POST方式处理图书添加业务
        departmentNo = request.POST.get('department.departmentNo') # 判断科室编号是否存在
        if self.primaryKeyExist(departmentNo):
            return JsonResponse({'success': False, 'message': '科室编号已经存在'})

        department = Department() # 新建一个科室信息对象然后获取参数
        department.departmentNo = departmentNo
        department.departmentName = request.POST.get('department.departmentName')
        department.madeDate = request.POST.get('department.madeDate')
        department.telephone = request.POST.get('department.telephone')
        department.chargeMan = request.POST.get('department.chargeMan')
        department.departmentDesc = request.POST.get('department.departmentDesc')
        department.save() # 保存科室信息信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class BackModifyView(BaseView):  # 后台更新科室信息
    def get(self, request, departmentNo):
        context = {'departmentNo': departmentNo}
        return render(request, 'Department/department_modify.html', context)


class ListView(BaseView):  # 后台科室信息列表
    def get(self, request):
        # 使用模板
        return render(request, 'Department/department_query_result.html')

    def post(self, request):
        # 获取当前要显示第几页和每页几条数据
        self.getPageAndSize(request)
        # 收集查询参数
        departmentNo = self.getStrParam(request, 'departmentNo')
        departmentName = self.getStrParam(request, 'departmentName')
        madeDate = self.getStrParam(request, 'madeDate')
        chargeMan = self.getStrParam(request, 'chargeMan')
        # 然后条件组合查询过滤
        departments = Department.objects.all()
        if departmentNo != '':
            departments = departments.filter(departmentNo__contains=departmentNo)
        if departmentName != '':
            departments = departments.filter(departmentName__contains=departmentName)
        if madeDate != '':
            departments = departments.filter(madeDate__contains=madeDate)
        if chargeMan != '':
            departments = departments.filter(chargeMan__contains=chargeMan)
        # 利用Paginator对查询结果集分页
        self.paginator = Paginator(departments, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        departments_page = self.paginator.page(self.currentPage)
        # 查询的结果集转换为列表
        departmentList = []
        for department in departments_page:
            department = department.getJsonObj()
            departmentList.append(department)
        # 构造模板页面需要的参数
        department_res = {
            'rows': departmentList,
            'total': self.recordNumber,
        }
        # 渲染模板页面显示
        return JsonResponse(department_res, json_dumps_params={'ensure_ascii':False})

class DeletesView(BaseView):  # 删除科室信息信息
    def get(self, request):
        return self.handle(request)

    def post(self, request):
        return self.handle(request)

    def handle(self, request):
        departmentNos = self.getStrParam(request, 'departmentNos')
        departmentNos = departmentNos.split(',')
        count = 0
        try:
            for departmentNo in departmentNos:
                Department.objects.get(departmentNo=departmentNo).delete()
                count = count + 1
            message = '%s条记录删除成功！' % count
            success = True
        except Exception as e:
            message = '数据库外键约束删除失败！'
            success = False
        return JsonResponse({'success': success, 'message': message})


class OutToExcelView(BaseView):  # 导出科室信息信息到excel并下载
    def get(self, request):
        # 收集查询参数
        departmentNo = self.getStrParam(request, 'departmentNo')
        departmentName = self.getStrParam(request, 'departmentName')
        madeDate = self.getStrParam(request, 'madeDate')
        chargeMan = self.getStrParam(request, 'chargeMan')
        # 然后条件组合查询过滤
        departments = Department.objects.all()
        if departmentNo != '':
            departments = departments.filter(departmentNo__contains=departmentNo)

PythonProject/templates/Department/department_frontquery_result.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
<title>科室信息查询</title>
<link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
<link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
<link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" media="screen">
</head>
<body style="margin-top:70px;">
<div class="container">
{% include 'header.html' %}
	<div class="row"> 
	<div class="col-md-3 wow fadeInLeft">
		<div class="page-header">
    		<h1>科室信息查询</h1>
		</div>
		<form name="departmentQueryForm" id="departmentQueryForm" action="{% url 'Department:frontList' %}" class="mar_t15" method="post">
			 {% csrf_token %}
			<div class="form-group">
				<label for="departmentNo">科室编号:</label>
				<input type="text" id="departmentNo" name="departmentNo" value="{{ departmentNo }}" class="form-control" placeholder="请输入科室编号">
			</div>
			<div class="form-group">
				<label for="departmentName">科室名称:</label>
				<input type="text" id="departmentName" name="departmentName" value="{{ departmentName }}" class="form-control" placeholder="请输入科室名称">
			</div>
			<div class="form-group">
				<label for="madeDate">成立日期:</label>
				<input type="text" id="madeDate" name="madeDate" class="form-control"  placeholder="请选择成立日期" value="{{ madeDate }}" onclick="SelectDate(this,'yyyy-MM-dd')" />
			</div>
			<div class="form-group">
				<label for="chargeMan">负责人:</label>
				<input type="text" id="chargeMan" name="chargeMan" value="{{ chargeMan }}" class="form-control" placeholder="请输入负责人">
			</div>
            <input type=hidden name=currentPage value="{{ currentPage }}" />
            <button type="submit" class="btn btn-primary">查询</button>
        </form>
	</div>

		<div class="col-md-9 wow fadeInDown" data-wow-duration="0.5s">
			<div>
				<!-- Nav tabs -->
				<ul class="nav nav-tabs" role="tablist">
			    	<li><a href="{% url 'Index:index' %}">首页</a></li>
			    	<li role="presentation" class="active"><a href="#departmentListPanel" aria-controls="departmentListPanel" role="tab" data-toggle="tab">科室信息列表</a></li>
			    	<li role="presentation" ><a href="{% url 'Department:frontAdd' %}" style="display:none;">添加科室信息</a></li>
				</ul>
			  	<!-- Tab panes -->
			  	<div class="tab-content">
				    <div role="tabpanel" class="tab-pane active" id="departmentListPanel">
				    		<div class="row">
				    			<div class="col-md-12 top5">
				    				<div class="table-responsive">
				    				<table class="table table-condensed table-hover">
				    					<tr class="success bold"><td>序号</td><td>科室编号</td><td>科室名称</td><td>成立日期</td><td>联系电话</td><td>负责人</td><td>操作</td></tr>
                                        {% for department in departments_page %}
 										<tr>
 											<td>{{ startIndex|add:forloop.counter }}</td>
 											<td>{{ department.departmentNo }}</td>
 											<td>{{ department.departmentName }}</td>
 											<td>{{ department.madeDate }}</td>
 											<td>{{ department.telephone }}</td>
 											<td>{{ department.chargeMan }}</td>
 											<td>
 												<a href="{% url 'Department:frontShow' department.departmentNo  %}"><i class="fa fa-info"></i>&nbsp;查看</a>&nbsp;
 												<a href="#" onclick="departmentEdit('{{ department.departmentNo }}');" style="display:none;"><i class="fa fa-pencil fa-fw"></i>编辑</a>&nbsp;
 												<a href="#" onclick="departmentDelete('{{ department.departmentNo }}');" style="display:none;"><i class="fa fa-trash-o fa-fw"></i>删除</a>
 											</td> 
 										</tr>
 										{% endfor %}
				    				</table>
				    				</div>
				    			</div>
				    		</div>

				    		<div class="row">
					            <div class="col-md-12">
						            <nav class="pull-left">
						                <ul class="pagination">
						                    <li><a href="#" onclick="GoToPage({{ currentPage|add:-1 }},{{ totalPage }}>);" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
                                            {% for page in pageList %}
                                            {% if currentPage == page %}
						                        <li class="active"><a href="#"  onclick="GoToPage({{ page }},{{ totalPage }});">{{ page }}</a></li>
						                    {% else %}
                                                <li><a href="#"  onclick="GoToPage({{ page }},{{ totalPage }});">{{ page }}</a></li>
                                            {% endif %}
                                            {% endfor %}
						                    <li><a href="#" onclick="GoToPage({{ currentPage|add:1 }},{{ totalPage }});"><span aria-hidden="true">&raquo;</span></a></li>
						                </ul>
						            </nav>
						            <div class="pull-right" style="line-height:75px;" >共有{{ recordNumber }}条记录，当前第{{ currentPage }}/{{ totalPage }} 页</div>
					            </div>
				            </div> 
				    </div>
				</div>
			</div>
		</div>
		</div>
	</div> 
<div id="departmentEditDialog" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" style="width:900px;" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><i class="fa fa-edit"></i>&nbsp;科室信息信息编辑</h4>
      </div>
      <div class="modal-body" style="height:450px; overflow: scroll;">
      	<form class="form-horizontal" name="departmentEditForm" id="departmentEditForm" enctype="multipart/form-data" method="post"  class="mar_t15">
		    {% csrf_token %}
		  <div class="form-group">
			 <label for="department_departmentNo_edit" class="col-md-3 text-right">科室编号:</label>
			 <div class="col-md-9"> 
			 	<input type="text" id="department_departmentNo_edit" name="department.departmentNo" class="form-control" placeholder="请输入科室编号" readOnly>
			 </div>
		  </div> 
		  <div class="form-group">
		  	 <label for="department_departmentName_edit" class="col-md-3 text-right">科室名称:</label>
		  	 <div class="col-md-9">
			    <input type="text" id="department_departmentName_edit" name="department.departmentName" class="form-control" placeholder="请输入科室名称">
			 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="department_madeDate_edit" class="col-md-3 text-right">成立日期:</label>
		  	 <div class="col-md-9">
                <div class="input-group date department_madeDate_edit col-md-12" data-link-field="department_madeDate_edit"  data-link-format="yyyy-mm-dd">
                    <input class="form-control" id="department_madeDate_edit" name="department.madeDate" size="16" type="text" value="" placeholder="请选择成立日期" readonly>
                    <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
                    <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                </div>
		  	 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="department_telephone_edit" class="col-md-3 text-right">联系电话:</label>
		  	 <div class="col-md-9">
			    <input type="text" id="department_telephone_edit" name="department.telephone" class="form-control" placeholder="请输入联系电话">
			 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="department_chargeMan_edit" class="col-md-3 text-right">负责人:</label>
		  	 <div class="col-md-9">
			    <input type="text" id="department_chargeMan_edit" name="department.chargeMan" class="form-control" placeholder="请输入负责人">
			 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="department_departmentDesc_edit" class="col-md-3 text-right">科室介绍:</label>
		  	 <div class="col-md-9">
			 	<textarea name="department.departmentDesc" id="department_departmentDesc_edit" style="width:100%;height:400px;"></textarea>
			 </div>
		  </div>
		</form> 
	    <style>#departmentEditForm .form-group {margin-bottom:5px;}  </style>
      </div>
      <div class="modal-footer"> 
      	<button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
      	<button type="button" class="btn btn-primary" onclick="ajaxDepartmentModify();">提交</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{% include 'footer.html' %}
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'plugins/wow.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-datetimepicker.min.js' %}"></script>
<script src="{% static 'plugins/locales/bootstrap-datetimepicker.zh-CN.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jsdate.js' %}"></script>
<script src="{% static 'tiny_mce/tiny_mce.js' %}"></script>
<script>
//实例化科室介绍编辑器
    tinyMCE.init({
        selector: "#department_departmentDesc_edit",
        theme: 'advanced',
        language: "zh",
        strict_loading_mode: 1,
    });
/*跳转到查询结果的某页*/
function GoToPage(currentPage,totalPage) {
    if(currentPage==0) return;
    if(currentPage>totalPage) return;
    document.departmentQueryForm.currentPage.value = currentPage;
    document.departmentQueryForm.submit();
}

/*可以直接跳转到某页*/
function changepage(totalPage)
{
    var pageValue=document.departmentQueryForm.pageValue.value;
    if(pageValue>totalPage) {
        alert('你输入的页码超出了总页数!');
        return ;
    }
    document.departmentQueryForm.currentPage.value = pageValue;
    documentdepartmentQueryForm.submit();
}

/*弹出修改科室信息界面并初始化数据*/
function departmentEdit(departmentNo) {
	$.ajax({
		url :  '/Department/update/' + departmentNo,
		type : "get",
		dataType: "json",
		success : function (department, response, status) {
			if (department) {
				$("#department_departmentNo_edit").val(department.departmentNo);
				$("#department_departmentName_edit").val(department.departmentName);
				$("#department_madeDate_edit").val(department.madeDate);
				$("#department_telephone_edit").val(department.telephone);
				$("#department_chargeMan_edit").val(department.chargeMan);
                tinyMCE.editors['department_departmentDesc_edit'].setContent(department.departmentDesc);
				$('#departmentEditDialog').modal('show');
			} else {
				alert("获取信息失败！");
			}
		}
	});
}

/*删除科室信息信息*/
function departmentDelete(departmentNo) {
    var csrf = $('input[name="csrfmiddlewaretoken"]').val();
	if(confirm("确认删除这个记录")) {
		$.ajax({
			type : "POST",
			url : "/Department/deletes",
			data : {
				departmentNos : departmentNo,
                "csrfmiddlewaretoken": csrf
			},
			success : function (obj) {
				if (obj.success) {
					alert("删除成功");
					$("#departmentQueryForm").submit();
					//location.href= basePath + "Department/frontlist";
				}
				else 
					alert(obj.message);
			},
		});
	}
}

/*ajax方式提交科室信息信息表单给服务器端修改*/
function ajaxDepartmentModify() {
    $("#department_departmentDesc_edit").text(tinyMCE.editors['department_departmentDesc_edit'].getContent());
	$.ajax({
		url :   '/Department/update/' + $("#department_departmentNo_edit").val(),
		type : "post",
		dataType: "json",
		data: new FormData($("#departmentEditForm")[0]),
		success : function (obj, response, status) {
            if(obj.success){
                alert("信息修改成功！");
                $("#departmentQueryForm").submit();
            }else{
                alert(obj.message);
            } 
		},
		processData: false,
		contentType: false,
	});
}

$(function(){
	/*小屏幕导航点击关闭菜单*/
    $('.navbar-collapse a').click(function(){
        $('.navbar-collapse').collapse('hide');
    });
    new WOW().init();

    /*成立日期组件*/
    $('.department_madeDate_edit').datetimepicker({
    	language:  'zh-CN',  //语言
    	format: 'yyyy-mm-dd',
    	minView: 2,
    	weekStart: 1,
    	todayBtn:  1,
    	autoclose: 1,
    	minuteStep: 1,
    	todayHighlight: 1,
    	startView: 2,
    	forceParse: 0
    });
})
</script>
</body>
</html>
